name: CI Builds

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: 'graalvm' # See 'Supported distributions' for available options
          java-version: '21'

      - name: Maven package
        run: |
          ./mvnw --batch-mode --no-transfer-progress package

      - name: Upload Jar
        uses: actions/upload-artifact@v3
        with:
          name: Upload jar
          path: |
            target/raton-loco-1.6.0.jar
